#$Shell = $Host.UI.RawUI
#$size = $Shell.WindowSize
#$size.width=70
#$size.height=25
#$Shell.WindowSize = $size
#$size = $Shell.BufferSize
#$size.width=70
#$size.height=5000
#$Shell.BufferSize = $size
#$shell.BackgroundColor = “Gray”
#$shell.ForegroundColor = “Black”
$dots = 'D:\dev\dots'
$bcnweb = 'D:\dev\DOTS\beacons\atiBeacon\trunk\atiBeaconWebApp'
$bcn = 'D:\dev\DOTS\beacons\atiBeacon\trunk\'
$flifo = 'D:\dev\DOTS\flifoapi'